export const REQUEST_COMMENT = 'REQUEST_COMMENT'
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT'

export const RECEIVE_COMMENT_VOTE = 'RECEIVE_COMMENT_VOTE'
export const REQUEST_COMMENT_VOTE = 'REQUEST_COMMENT_VOTE'

export const REQUESt_COMMENT_EDIT = 'REQUES_COMMENT_EDIT'
export const RECEIVE_COMMNET_EDIT = 'RECEIVE_COMMNET_EDIT'

export const REQUEST_COMMENT_DELETE = 'REQUEST_COMMENT_DELETE'
export const RECEIVE_COMMENT_DELETE = 'RECEIVE_COMMENT_DELETE'

export const REQUEST_COMMENT_CREAT = 'REQUEST_COMMENT_CREAT'
export const RECEIVE_COMMNET_CREAT = 'RECEIVE_COMMNET_CREAT'

export const ORDER_COMMENTS = 'ORDER_COMMENTS'